#https://hub.docker.com/_/postgres
services:
  db:
    image: postgres:17-alpine3.20
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./bdd:/var/lib/postgresql/data
    restart: always
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: user
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
    depends_on:
      - db
    restart: always